import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
test('guest booking, account, administration and screenshots', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await expect.poll(async () => {
    try { return (await request.get('http://127.0.0.1:8080/api/health')).status(); }
    catch { return 0; }
  }, { timeout: 60000 }).toBe(200);
  await mkdir('docs/screenshots', { recursive: true });
  await page.goto('/');
  await expect(page.locator('html')).toHaveAttribute('lang', 'uk');
  await expect(page.getByRole('heading', { name: 'Знайдемо номери під ваші побажання' })).toBeVisible();
  await page.getByRole('button', { name: 'English', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Find your perfect stay' })).toBeVisible();
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Find your perfect stay' })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/home-en.png', fullPage: true });
  await page.getByRole('button', { name: 'Українська', exact: true }).click();
  await page.screenshot({ path: 'docs/screenshots/home.png', fullPage: true });
  await page.goto('/rooms');
  await expect(page.locator('.room-card').first()).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/catalog.png', fullPage: true });
  await page.getByRole('button', { name: 'English', exact: true }).click();
  await expect(page.getByText('Rooms for your stay', {exact:true})).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/catalog-en.png', fullPage: true });
  await page.getByRole('button', { name: 'Українська', exact: true }).click();
  await page.locator('.room-card__description').first().click();
  await expect(page.getByRole('button', { name: 'Забронювати', exact: true })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/room.png', fullPage: true });
  await page.getByRole('button', { name: 'English', exact: true }).click();
  await expect(page.getByRole('button', {name:'Book this room',exact:true})).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/room-en.png', fullPage: true });
  await page.getByRole('button', { name: 'Українська', exact: true }).click();
  await page.goto('/login/signIn');
  await page.locator('input[name=email]').fill('guest@example.com');
  await page.getByRole('button', { name: 'English', exact: true }).click();
  await expect(page.locator('input[name=email]')).toHaveValue('guest@example.com');
  await page.getByRole('button', { name: 'Українська', exact: true }).click();
  await page.locator('input[name=password]').fill('DemoGuest123!');
  await page.locator('form').getByRole('button', { name: 'Увійти', exact: true }).click();
  await expect(page).toHaveURL('/');
  await page.goto('/rooms');
  await page.locator('.room-card__description').first().click();
  await page.getByRole('button', { name: 'Забронювати', exact: true }).click();
  await expect(page.locator('.MuiDialog-root')).toBeVisible();
  const userId = await page.evaluate(() => localStorage.getItem('user-local-id'));
  await page.goto(`/profile/${userId}/booking`);
  await expect(page.locator('.booking-card').first()).toBeVisible();
  await expect(page.getByText('Підтверджено · очікує оплати').first()).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/bookings.png', fullPage: true });
  await page.getByRole('button', { name: 'English', exact: true }).click();
  await expect(page.getByText('Confirmed · awaiting payment').first()).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/bookings-en.png', fullPage: true });
  await page.getByRole('button', { name: 'Українська', exact: true }).click();
  await page.getByRole('button', { name: 'Скасувати бронювання' }).first().click();
  await expect(page.getByText('Скасовано', { exact: true }).first()).toBeVisible();
  await page.evaluate(() => localStorage.clear());
  await page.goto('/login/signIn');
  await page.locator('input[name=email]').fill('admin@example.com');
  await page.locator('input[name=password]').fill('DemoAdmin123!');
  await page.locator('form').getByRole('button', { name: 'Увійти', exact: true }).click();
  await expect(page).toHaveURL('/');
  const adminId = await page.evaluate(() => localStorage.getItem('user-local-id'));
  await page.goto(`/profile/${adminId}/dashboard`);
  await expect(page.getByRole('heading', { name: 'Панель адміністратора', exact: true })).toBeVisible();
  await expect(page.getByText('Список номерів', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/admin.png', fullPage: true });
  await page.getByRole('button', { name: 'English', exact: true }).click();
  await expect(page.getByRole('heading', {name:'Hotel dashboard',exact:true})).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/admin-en.png', fullPage: true });
  await page.getByRole('button', { name: 'Українська', exact: true }).click();
  await page.getByRole('button', {name:'Редагувати номер',exact:true}).first().click();
  await expect(page.locator('input[name=price]')).toBeVisible();
  await page.locator('input[name=price]').fill('9991');
  await page.getByRole('button', {name:'Оновити',exact:true}).last().click();
  await expect(page.locator('.MuiDialog-root')).not.toBeVisible();
  await expect(page.locator('td').filter({hasText:/9\s*991/}).first()).toBeVisible();
  await page.goto('/profile');
  await expect(page).toHaveURL(`/profile/${adminId}`);
  await page.evaluate(() => localStorage.clear());
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/rooms');
  await expect(page.locator('.room-card').first()).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole('button', { name: 'English', exact: true }).click();
  await expect(page.getByText('Dates, guests and filters', {exact:true})).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/mobile-en.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
